<?php ///[i18n:Long Text Translation]
///such as: 'Sorry, we are unable to reset password ...' => 'Sorry, we are unable to reset password for the provided email address.',

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

	///\vendor\yongtiger\yii2-tree-manager\src\widgets\TreeView.php
	'Create a root node' => '创建根节点',
	'Create' => '创建',
	'Collapse all' => '折叠全部',
	'Expand all' => '展开全部',
	'View' => '查看',
	'Update' => '更新',
	'Create' => '创建',
	'Delete' => '删除',
	'Delete All' => '删除全部',

];
